version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/bff-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/users-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/shared/Synapse"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/shared/Bowltie"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/shared/Bugle"
    schedule:
      interval: "weekly"
